version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis_protocol3/protocol3_dataset_definition_patients.py --output output/dataset_patients.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_patients.csv.gz
